
spring:
  config.activate.on-profile: local
  datasource:
    url: ${URL}
    username: root
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
override.value: ${override.value}