spring:
  datasource:
    url: jdbc:mysql://fastcampus-rds.clriygaktsla.ap-northeast-2.rds.amazonaws.com:3306/awsfirst
    username: root
    password: xron0610
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
override.value: what