spring:
  datasource:
    url: jdbc:mariadb://svc.gksl2.cloudtype.app:32660/awsfirsttest
    username: root
    password: test
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
      show-sql: true
override.value: hello